Vijiproject/OnlineDoctorsAppointmentBooking/Controllers/DoctorController.cs
using OnlineDoctorsAppointmentBooking.Models;
using OnlineDoctorsAppointmentBooking.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace OnlineBookingDoctorsAppointment.Controllers
{
    public class DoctorController : Controller
    {
        private ApplicationDbContext dbContext = null;
        public DoctorController()
        {
            dbContext = new ApplicationDbContext();
        }
        [HttpGet]
        public ActionResult DoctorLogin()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DoctorLogin(ViewModel_Login loginViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            else
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }
                else
                {
                    var doctor = dbContext.Doctors.FirstOrDefault(e => e.EmailId == loginViewModel.UserId || e.DoctorId.ToString() == loginViewModel.UserId);
                    if (doctor == null)
                    {
                        loginViewModel.LoginErrorMessage = "Invalid Sap Id or Mail Id";
                        return View("DoctorLogin", loginViewModel);
                    }
                    else if (doctor.PassWord == loginViewModel.Password)
                    {
                        Session["doctor"] = doctor;
                        Session["doctorId"] = doctor.Id;
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        loginViewModel.LoginErrorMessage = "Incorrect Password....Try again!!!!";
                        return View("DoctorLogin", loginViewModel);
                    }
                }
            }
        }
        public ActionResult Index()
        {
            var doctor = (Doctor)Session["doctor"];
            return View(doctor);
        }
        public ActionResult MyAppointments()
        {
            int id = (int)Session["doctorId"];
            var appointments = dbContext.AppointmentDetails.Include(a=>a.Doctor).Include(a=>a.Employee).Include(a=>a.TimeSlots).Where(a => a.DoctorId == id).ToList();
            return View(appointments);
        }
       
    }
}

Vijiproject/OnlineDoctorsAppointmentBooking/Controllers/EmployeeController.cs
using OnlineDoctorsAppointmentBooking.Models;
using OnlineDoctorsAppointmentBooking.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace OnlineBookingDoctorsAppointment.Controllers
{
    public class EmployeeController : Controller
    {
        private ApplicationDbContext dbContext = null;
        public EmployeeController()
        {
            dbContext = new ApplicationDbContext();
        }
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult EmployeeLogin()
        {
            return View();
        }
        [HttpPost]
        public ActionResult EmployeeLogin(ViewModel_Login loginViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            else
            {
                var employee = dbContext.Employees.FirstOrDefault(e => e.EmailId == loginViewModel.UserId || e.SapId.ToString() == loginViewModel.UserId);
                if (employee == null)
                {
                    loginViewModel.LoginErrorMessage = "Invalid Sap Id or Mail Id";
                    return View("EmployeeLogin", loginViewModel);
                }
                else if (employee.Password == loginViewModel.Password)
                {
                    Session["employee"] = employee;
                    Session["employeeId"] = employee.Id;
                    return RedirectToAction("Index");
                }
                else
                {
                    loginViewModel.LoginErrorMessage = "Incorrect Password....Try again!!!!";
                    return View("EmployeeLogin", loginViewModel);
                }
            }
        }
        public ActionResult MyDetails()
        {
            ViewBag.employee = Session["employee"];
            return View();
        }
        [HttpGet]
        public ActionResult Update(int id)
        {
            var employee = dbContext.Employees.FirstOrDefault(e => e.Id == id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }
        [HttpPost]
        public ActionResult Update(Employee employee)
        {
            if (!ModelState.IsValid)
            {
                return View(employee);
            }
            var empInDb = dbContext.Employees.FirstOrDefault(e => e.Id == employee.Id);
            if (empInDb != null)
            {
                empInDb.EmployeeFirstName = employee.EmployeeFirstName;
                empInDb.EmployeeLastName = employee.EmployeeLastName;
                empInDb.EmailId = employee.EmailId;
                empInDb.Password = employee.Password;
                empInDb.MobileNumber = employee.MobileNumber;
                empInDb.DateOfBirth = employee.DateOfBirth;
                empInDb.BloodGroup = employee.BloodGroup;
                empInDb.Location = employee.Location;
                empInDb.Location = employee.Location;
            }

            dbContext.SaveChanges();
            //Session["employee"] = empInDb;
            return RedirectToAction("Index");

        }
        [HttpGet]
        public ActionResult BookAppointment()
        {
            ViewBag.Location = ListCity();
            ViewBag.Specialization = ListSpecialization();
            return View();
        }
        [HttpPost]
        public ActionResult BookAppointment(Doctor doctor)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Location = ListCity();
                ViewBag.Specialization = ListSpecialization();
                return View();
            }
            var doctors = dbContext.Doctors.Where(d => d.Location == doctor.Location && d.Specialization == doctor.Specialization && d.IsAvailable == true).ToList();
            if (doctors.Count != 0)
            {
                return View("DisplayDoctors", doctors);
            }
            else
            {
                return Content("Doctors not found");
            }
        }
        [HttpPost]
        public ActionResult SearchByDoctorName(string search)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Location = ListCity();
                ViewBag.Specialization = ListSpecialization();
                return View();
            }
            var doctor = dbContext.Doctors.Where(d => (d.DoctorFirstName.Contains(search) || d.DoctorLastName.Contains(search)) && d.IsAvailable == true).ToList();
            if (doctor.Count != 0)
            {
                return View("DisplayDoctors", doctor);
            }
            else
            {
                return Content("Doctors not found");
            }
        }
        public ActionResult DisplayDoctors(Doctor doctor)
        {

            return View(doctor);
        }
        [HttpGet]
        public ActionResult TimeSlots(int id)
        {
            Session["doctorId"] = id;
            var appointment = new AppointmentDetails();
            ViewBag.TimeSlotsId = ListTimeSlot();
            return View(appointment);
        }
        [HttpPost]
        public ActionResult TimeSlots(AppointmentDetails appointment)
        {
            var details = dbContext.AppointmentDetails.Where(a => a.AppointmentDate == appointment.AppointmentDate).ToList();
            Random random = new Random();
            appointment.AppointmentNumber = random.Next(1000, 9000);
            appointment.StatusOfBooking = "Booked";
            appointment.EmployeeId = (int)Session["employeeId"];
            appointment.DoctorId = (int)Session["doctorId"];
            if (details.Count != 0)
            {
                var record = details.Where(a => a.TimeSlotsId == appointment.TimeSlotsId).ToList();
                if (record.Count != 0)
                {
                    var patient = record.Where(p => p.EmployeeId == appointment.EmployeeId && p.DoctorId == appointment.DoctorId).ToList();
                    if (patient.Count != 0)
                    {
                        return Content("This slot was already booked");
                    }
                }
            }
                dbContext.AppointmentDetails.Add(appointment);
                dbContext.SaveChanges();
            return RedirectToAction("Confirmation");         
        }
        public ActionResult Confirmation()
        {
            return View();
        }
        public ActionResult CancelAppointment(int id)
        {
            var patients = dbContext.AppointmentDetails.Find(id);
            dbContext.AppointmentDetails.Remove(patients);
            dbContext.SaveChanges();
            return View();
        }
        public ActionResult BookingDetails()
        {
            int id = (int)Session["employeeId"];
            var details = dbContext.AppointmentDetails.Include(a => a.TimeSlots).Include(a => a.Employee).Include(a => a.Doctor).Where(a=>a.EmployeeId==id).ToList();
            return View(details);
        }
        [NonAction]
        public IEnumerable<SelectListItem> ListCity()
        {
            var Location = (from l in dbContext.Doctors.AsEnumerable().GroupBy(l => l.Location)
                            select new SelectListItem
                            {
                                Text = l.Key
                            }).ToList();

            Location.Insert(0, new SelectListItem { Text = "--Select Healthcare Location--", Value = "0", Disabled = true, Selected = true });

            return Location;
        }
        [NonAction]
        public IEnumerable<SelectListItem> ListSpecialization()
        {
            var Specialization = (from s in dbContext.Doctors.AsEnumerable().GroupBy(s => s.Specialization)
                                  select new SelectListItem
                                  {
                                      Text = s.Key
                                  }).ToList();

            Specialization.Insert(0, new SelectListItem { Text = "--Select Specialization--", Value = "0", Disabled = true, Selected = true });

            return Specialization;

        }
        [NonAction]
        public IEnumerable<SelectListItem> ListTimeSlot()
        {
            var TimeSlot = (from m in dbContext.TimeSlots.AsEnumerable()
                            select new SelectListItem
                            {
                                Text = m.TimeSlot,
                                Value = m.Id.ToString()
                            }).ToList();

            TimeSlot.Insert(0, new SelectListItem { Text = "---Select---", Value = "0", Disabled = true, Selected = true });

            return TimeSlot;
        }
        
    }
}

Vijiproject/OnlineDoctorsAppointmentBooking/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineDoctorsAppointmentBooking.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Vijiproject/OnlineDoctorsAppointmentBooking/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Vijiproject/OnlineDoctorsAppointmentBooking/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Vijiproject/OnlineDoctorsAppointmentBooking/Views/Home/Index.cshtml
@{
    //ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<img src="~/Images/Capture.PNG" />
<br />

<div class="row">
    <div class="col-md-3">
        <div class="row">
            <div class="col-md-12">
                <center>
                    <img src="~/Images/Home/employee.png" style="height:150px;width:100px" />
                    <h3>@Html.ActionLink("Employee Login", "EmployeeLogin", "Employee")</h3>
                </center>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <center>
                    <img src="~/Images/Home/doctor.png" style="padding-top:10px; height:150px;width:100px" />
                    <h3>@Html.ActionLink("Doctor Login", "DoctorLogin", "Doctor")</h3>
                </center>
            </div>
        </div>
        @*<div class="row">
                <div class="col-md-12">
                    <center>
                        <img src="~/Images/Home/Admin.jfif" style="padding-top:25px; height:100px;width:75px" />
                        <h3>@Html.ActionLink("Admin Login", "AdminLogin", "Admin")</h3>
                    </center>
                </div>
            </div>*@
    </div>

    <div class="col-md-9">
        <br />
        <center>
            <div class="row">
                <div class="col-md-8 col-md-offset-4">
                    <div id="carouselExampleControls" class="carousel slide" data-interval="2000" data-ride="carousel">
                        <div class="carousel-inner">
                            <div class="item active">
                                <img src="~/Images/Carousel/carousel2.jpg" class="d-block w-100 img-responsive" style="height:400px" />
                            </div>
                            <div class="item">
                                <img src="~/Images/Carousel/carousel.jfif" class="d-block w-100 img-responsive" style="height:400px;width:900px" />
                            </div>
                            <div class="item">
                                <img src="~/Images/Carousel/carousel4.jpg" class="d-block w-100 img-responsive" style="height:400px;width:900px" />
                            </div>
                            <div class="item">
                                <img src="~/Images/Carousel/carousel1.jpg" class="d-block w-100 img-responsive" style="height:400px;width:900px" />
                            </div>
                            <div class="item">
                                <img src="~/Images/Carousel/carousel3.jpg" class="d-block w-100 img-responsive" style="height:400px;width:900px" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </center>
    </div>
</div>
<br />
<div class="container" style="font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif">
    <h4>
        <b>
            <i>
                HCL Healthcare, a delivery arm of HCL Groups, is a nationwide network of multi-specialty clinics with a key focus on corporate health - adopting global best practices for medical quality and training,using evidence-based treatments and integrating advanced technology.HCL Healthcare’s primary offerings include Preventive Health Solutions, Managed Care Plans, Dentistry solutions,    and Wellness & Wellbeing programs which aim to provide the whole continuum of care for chronic and acute diseases.
                Being a trusted long-term care partner, HCL Healthcare is rapidly and constantly evolving to build digitally enabled health solutions for corporate India.
                <br />
                <br />
                HCL Healthcare will offer unmatched patient experience and outcomes by adopting global best practices for medical quality and training,using evidence based treatments and integrating advanced technology.
                HCL Healthcare is determined to be the trusted long-term care partner for people in health or illness.
            </i>
        </b>
    </h4>
</div>
<br />
<center>
    <div class="row">
        <div class="col-md-4">
            <img src="~/Images/Achievements/image2Heart.png" alt="Heart" style="width:50%">
            <p>25 World Class Heart Institutes</p>
        </div>
        <div class="col-md-4">
            <img src="~/Images/Achievements/image3Kidney.png" alt="Kidney" style="width:50%">
            <p>7000 Kidney Transplants performed</p>
        </div>
        <div class="col-md-4">
            <img src="~/Images/Achievements/image4Neuro.png" alt="Neuro" style="width:50%">
            <p>10,000 Neurosurgeries performed per year</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <img src="~/Images/Achievements/image5tissue.png" alt="Tissue" style="width:50%">
            <p>1000 patients successfully treated through exultant            </p>
        </div>
        <div class="col-md-4">
            <img src="~/Images/Achievements/image6hearingaid.png" alt="Hearing Aid" style="width:50%">
            <p>700 Cochlear implant surgery and reached a new milestone in the history of aiding hearing impaired in India</p>
        </div>
        <div class="col-md-4">
            <img src="~/Images/Achievements/image7joints.png" alt="Joints" style="width:50%">
            <p>Completed over 10,000 Joint Replacement Surgeries</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <img src="~/Images/Achievements/image8minorsurgeries.png" alt="Mino Surgeries" style="width:50%">
            <p>1 Million minor surgical procedures performed</p>
        </div>
        <div class="col-md-4">
            <img src="~/Images/Achievements/img9solidorgan.png" alt="Solid Organ" style="width:50%">
            <p>1200 solid organ transplants in one year</p>
        </div>
        <div class="col-md-4">
            <img src="~/Images/Achievements/img10.png" alt="Lives" style="width:50%">
            <p>
                Touched over 42 Million lives and still counting
            </p>
        </div>
    </div>

</center>